title = "Dreaming Spires"

[params]
fathom_id = "testvalue"

[params.nav]
navbar = [
	{ url = "/", name = "Home" },
	{ url = "/our_services", name = "Our Services" },
	{ url = "/portfolio", name = "Portfolio" },
	{ url = "/develop_with_us", name = "Develop with Us" }
]

hotlinks = [
	{ url = "/contact", name = "Contact Us" }
]

footer = [
    { url = "/", name = "Home" },
    { url = "/#about", name = "About" },
    { url = "/developer_faq", name = "Developer FAQ" },
    { url = "/client_faq", name = "Client FAQ" },
    { url = "/contact", name = "Contact" },
    { url = "/privacy_policy", name = "Privacy Policy" },
]

[permalinks]
"/portfolio/" = "/portfolio/{{ .Date.Format `2006/01/02` }}/{{ path.Base .Path }}/"

[[tasks]]
input = [".md", ".html"]
output = ".html"
template = ".html"
preprocess.md = "mdtohtml --unsafe"
static_dir = "static"
output_dir = "public"
ugly_urls = true

[[tasks]]
input = [".scss"]
output = ".css"
preprocess.scss = "sassc"
output_dir = "public/assets"
ugly_urls = true

[[tasks]]
input = [".jpg", ".jpeg", ".png"]
output = ".jpg"
preprocess.jpg = "magick /dev/stdin -strip -interlace Plane -gaussian-blur 0.05 -quality 85% /dev/stdout"
output_dir = "public"
ugly_urls = true
