title = "Example website"
urls = ["gemini://example.com"]

[params]
fathom_id = "testvalue"

[params.navbar]
items = [
	{ url = "/", name = "Home" },
	{ url = "/our_services", name = "Our Services" },
	{ url = "/portfolio", name = "Portfolio" },
	{ url = "/develop_with_us", name = "Develop with Us" }
]

buttons = [
	{ url = "/contact", name = "Contact Us" }
]

footer = [
    { url = "/", name = "Home" },
    { url = "/#about", name = "About" },
    { url = "/developer_faq", name = "Developer FAQ" },
    { url = "/client_faq", name = "Client FAQ" },
    { url = "/contact", name = "Contact" },
    { url = "/privacy_policy", name = "Privacy Policy" },
]

[feeds]
"/" = "Example feed"

[permalinks]
"/" = "/{{ .Date.Format `2006/01/02` }}/{{ path.Base .Path }}/"

[[tasks]]
input = [".gmi"]
output = ".gmi"
template = ".gmi"
static_dir = "static"
output_dir = "public"

[[tasks]]
input = [".html"]
output = ".html"
template = ".html"
preprocess.md = "markdown"
static_dir = "static"
output_dir = "public"

[[tasks]]
input = [".scss"]
output = ".css"
preprocess.scss = "sassc"
output_dir = "public"
ugly_urls = true
